#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : ntp
Version  : 4.2.8p17
Release  : 9
URL      : https://archive.ntp.org/ntp4/ntp-4.2/ntp-4.2.8p17.tar.gz
Source0  : https://archive.ntp.org/ntp4/ntp-4.2/ntp-4.2.8p17.tar.gz
Summary  : libevent_pthreads adds pthreads-based threading support to libevent
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 LGPL-3.0 MIT
Requires: ntp-bin = %{version}-%{release}
Requires: ntp-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : intltool-dev
BuildRequires : libcap-dev
BuildRequires : pkgconfig(libevent_pthreads)
BuildRequires : pkgconfig(zlib)
BuildRequires : ruby
BuildRequires : sed
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Submit patches, bug reports, and enhancement requests via
http://bugs.ntp.org
The ntp Distribution Base Directory

%package bin
Summary: bin components for the ntp package.
Group: Binaries
Requires: ntp-license = %{version}-%{release}

%description bin
bin components for the ntp package.


%package doc
Summary: doc components for the ntp package.
Group: Documentation

%description doc
doc components for the ntp package.


%package license
Summary: license components for the ntp package.
Group: Default

%description license
license components for the ntp package.


%prep
%setup -q -n ntp-4.2.8p17
cd %{_builddir}/ntp-4.2.8p17

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1686076541
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}  CFLAGS+=-fcommon

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check CFLAGS+="-fcommon -Wp,-D_FORTIFY_SOURCE=0"

%install
export SOURCE_DATE_EPOCH=1686076541
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ntp
cp %{_builddir}/ntp-%{version}/libjsmn/LICENSE %{buildroot}/usr/share/package-licenses/ntp/7b20de0c23cbc9a17c3af51ddac5c3ad8182f8b1 || :
cp %{_builddir}/ntp-%{version}/sntp/libevent/LICENSE %{buildroot}/usr/share/package-licenses/ntp/0f375374b877550ade2e001905a1f9c9b7128714 || :
cp %{_builddir}/ntp-%{version}/sntp/libevent/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/ntp/cc31ae51223e291f3f7389a4c96b2cf4c1e62757 || :
cp %{_builddir}/ntp-%{version}/sntp/libevent/cmake/Copyright.txt %{buildroot}/usr/share/package-licenses/ntp/b7708e46727dc00ced77b6421d1f4b4e4045c12d || :
cp %{_builddir}/ntp-%{version}/sntp/libopts/COPYING.gplv3 %{buildroot}/usr/share/package-licenses/ntp/33eb5592147416092b4bad559d7dff2b4186f5f2 || :
cp %{_builddir}/ntp-%{version}/sntp/libopts/COPYING.lgplv3 %{buildroot}/usr/share/package-licenses/ntp/d981a9ec80bd5ecd5f7cf8f53ca8484418b2d8af || :
cp %{_builddir}/ntp-%{version}/sntp/libopts/COPYING.mbsd %{buildroot}/usr/share/package-licenses/ntp/d5a774e469a622f792d89922ece780e651623731 || :
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/calc_tickadj
rm -f %{buildroot}*/usr/bin/ntp-keygen
rm -f %{buildroot}*/usr/bin/ntp-wait
rm -f %{buildroot}*/usr/bin/ntpd
rm -f %{buildroot}*/usr/bin/ntpdc
rm -f %{buildroot}*/usr/bin/ntpq
rm -f %{buildroot}*/usr/bin/ntptime
rm -f %{buildroot}*/usr/bin/ntptrace
rm -f %{buildroot}*/usr/bin/sntp
rm -f %{buildroot}*/usr/bin/tickadj
rm -f %{buildroot}*/usr/bin/update-leap
rm -f %{buildroot}*/usr/share/ntp/lib/NTP/Util.pm
rm -f %{buildroot}*/usr/share/man/man1/calc_tickadj.1
rm -f %{buildroot}*/usr/share/man/man1/ntp-keygen.1
rm -f %{buildroot}*/usr/share/man/man1/ntp-wait.1
rm -f %{buildroot}*/usr/share/man/man1/ntpd.1
rm -f %{buildroot}*/usr/share/man/man1/ntpdc.1
rm -f %{buildroot}*/usr/share/man/man1/ntpq.1
rm -f %{buildroot}*/usr/share/man/man1/ntptrace.1
rm -f %{buildroot}*/usr/share/man/man1/sntp.1
rm -f %{buildroot}*/usr/share/man/man1/update-leap.1
rm -f %{buildroot}*/usr/share/man/man5/ntp.conf.5
rm -f %{buildroot}*/usr/share/man/man5/ntp.keys.5

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ntpdate

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/ntp/*
/usr/share/doc/sntp/sntp.html

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ntp/0f375374b877550ade2e001905a1f9c9b7128714
/usr/share/package-licenses/ntp/33eb5592147416092b4bad559d7dff2b4186f5f2
/usr/share/package-licenses/ntp/7b20de0c23cbc9a17c3af51ddac5c3ad8182f8b1
/usr/share/package-licenses/ntp/b7708e46727dc00ced77b6421d1f4b4e4045c12d
/usr/share/package-licenses/ntp/cc31ae51223e291f3f7389a4c96b2cf4c1e62757
/usr/share/package-licenses/ntp/d5a774e469a622f792d89922ece780e651623731
/usr/share/package-licenses/ntp/d981a9ec80bd5ecd5f7cf8f53ca8484418b2d8af
