#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ntp
Version  : 4.2.8p15
Release  : 7
URL      : http://archive.ntp.org/ntp4/ntp-4.2/ntp-4.2.8p15.tar.gz
Source0  : http://archive.ntp.org/ntp4/ntp-4.2/ntp-4.2.8p15.tar.gz
Summary  : libevent_pthreads adds pthreads-based threading support to libevent
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GPL-3.0 LGPL-3.0 MIT
Requires: ntp-bin = %{version}-%{release}
Requires: ntp-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : intltool-dev
BuildRequires : libcap-dev
BuildRequires : pkgconfig(libevent_pthreads)
BuildRequires : pkgconfig(zlib)
BuildRequires : ruby
BuildRequires : sed
Patch1: ntp-4.2.8p15-fix-build-for-dynamic-stack-size-glibc-2.34-and-greater.patch

%description
Submit patches, bug reports, and enhancement requests via
http://bugs.ntp.org
The ntp Distribution Base Directory

%package bin
Summary: bin components for the ntp package.
Group: Binaries
Requires: ntp-license = %{version}-%{release}

%description bin
bin components for the ntp package.


%package doc
Summary: doc components for the ntp package.
Group: Documentation

%description doc
doc components for the ntp package.


%package license
Summary: license components for the ntp package.
Group: Default

%description license
license components for the ntp package.


%prep
%setup -q -n ntp-4.2.8p15
cd %{_builddir}/ntp-4.2.8p15
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1670261225
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}  CFLAGS+=-fcommon

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check CFLAGS+="-fcommon -Wp,-D_FORTIFY_SOURCE=0"

%install
export SOURCE_DATE_EPOCH=1670261225
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ntp
cp %{_builddir}/ntp-%{version}/COPYRIGHT %{buildroot}/usr/share/package-licenses/ntp/2209cf7c235e8a8e705c123b33c03707f47b9049
cp %{_builddir}/ntp-%{version}/libjsmn/LICENSE %{buildroot}/usr/share/package-licenses/ntp/7b20de0c23cbc9a17c3af51ddac5c3ad8182f8b1
cp %{_builddir}/ntp-%{version}/sntp/COPYRIGHT %{buildroot}/usr/share/package-licenses/ntp/2209cf7c235e8a8e705c123b33c03707f47b9049
cp %{_builddir}/ntp-%{version}/sntp/libevent/LICENSE %{buildroot}/usr/share/package-licenses/ntp/0f375374b877550ade2e001905a1f9c9b7128714
cp %{_builddir}/ntp-%{version}/sntp/libopts/COPYING.gplv3 %{buildroot}/usr/share/package-licenses/ntp/e8353ab286a6bcbb218d9df15d8aa68346ef5cf0
cp %{_builddir}/ntp-%{version}/sntp/libopts/COPYING.lgplv3 %{buildroot}/usr/share/package-licenses/ntp/8ca3cbd336e9a13d5ee05753567d9261af4066a3
cp %{_builddir}/ntp-%{version}/sntp/libopts/COPYING.mbsd %{buildroot}/usr/share/package-licenses/ntp/76f15ccf78ed039d563200c8db64f85d17c3d7cb
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/calc_tickadj
rm -f %{buildroot}*/usr/bin/ntp-keygen
rm -f %{buildroot}*/usr/bin/ntp-wait
rm -f %{buildroot}*/usr/bin/ntpd
rm -f %{buildroot}*/usr/bin/ntpdc
rm -f %{buildroot}*/usr/bin/ntpq
rm -f %{buildroot}*/usr/bin/ntptime
rm -f %{buildroot}*/usr/bin/ntptrace
rm -f %{buildroot}*/usr/bin/sntp
rm -f %{buildroot}*/usr/bin/tickadj
rm -f %{buildroot}*/usr/bin/update-leap
rm -f %{buildroot}*/usr/share/ntp/lib/NTP/Util.pm
rm -f %{buildroot}*/usr/share/man/man1/calc_tickadj.1
rm -f %{buildroot}*/usr/share/man/man1/ntp-keygen.1
rm -f %{buildroot}*/usr/share/man/man1/ntp-wait.1
rm -f %{buildroot}*/usr/share/man/man1/ntpd.1
rm -f %{buildroot}*/usr/share/man/man1/ntpdc.1
rm -f %{buildroot}*/usr/share/man/man1/ntpq.1
rm -f %{buildroot}*/usr/share/man/man1/ntptrace.1
rm -f %{buildroot}*/usr/share/man/man1/sntp.1
rm -f %{buildroot}*/usr/share/man/man1/update-leap.1
rm -f %{buildroot}*/usr/share/man/man5/ntp.conf.5
rm -f %{buildroot}*/usr/share/man/man5/ntp.keys.5

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ntpdate

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/ntp/*
/usr/share/doc/sntp/sntp.html

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ntp/0f375374b877550ade2e001905a1f9c9b7128714
/usr/share/package-licenses/ntp/2209cf7c235e8a8e705c123b33c03707f47b9049
/usr/share/package-licenses/ntp/76f15ccf78ed039d563200c8db64f85d17c3d7cb
/usr/share/package-licenses/ntp/7b20de0c23cbc9a17c3af51ddac5c3ad8182f8b1
/usr/share/package-licenses/ntp/8ca3cbd336e9a13d5ee05753567d9261af4066a3
/usr/share/package-licenses/ntp/e8353ab286a6bcbb218d9df15d8aa68346ef5cf0
